version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - test_database:
          filters:
            branches:
              only: main
      - test_server:
          requires:
            - test_database
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          requires:
            - test_server
          filters:
            branches:
              only: main

jobs:
  test_database:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Connect to the database
          command: node db/connect.js

  test_server:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start server
          command: node app.js

  heroku/deploy-via-git:
    executor:
      name: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git
