version: 2.1
jobs:
  test_and_deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run database and server tests
          command: |
            npx jest --detectOpenHandles tests/connectDB.test.js
            npx jest --detectOpenHandles tests/serverLive.test.js
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run:
          name: Deploy to Heroku
          command: heroku/deploy-via-git

workflows:
  version: 2
  heroku_deploy:
    jobs:
      - test_and_deploy:
          filters:
            branches:
              only: main
