version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - test_code:
          name: Run Tests
      - heroku/deploy-via-git:
          name: Deploy to Heroku
          when: <<pipeline.parameters.tests_passed>>

jobs:
  test_code:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
          no_output_timeout: 10m
          when: <<pipeline.parameters.tests_enabled>>

parameters:
  tests_enabled:
    description: 'Enable running tests'
    default: true

  tests_passed:
    description: 'Tests passed'
    default: << pipeline.parameters.tests_enabled >>
    type: boolean
    options:
      - true
      - false
