version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  deploy_to_heroku:
    executor:
      name: heroku/default
    steps:
      - checkout
      - heroku/setup-heroku:
          version: stable
      - run:
          name: Deploy to Heroku
          command: heroku/deploy-via-git

workflows:
  version: 2
  heroku_deploy:
    jobs:
      - deploy_to_heroku:
          filters:
            branches:
              only: main
