version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - test_code
      - heroku/deploy-via-git:
          requires:
            - test_code
          filters:
            branches:
              only: main

jobs:
  test_code:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Start server
          command: npm start &
      - run:
          name: Wait for server to start
          command: sleep 10 # Adjust the sleep duration as needed

