version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - test_code:
          filters:
            branches:
              only: main
      - deploy_to_heroku:
          requires:
            - test_code
          filters:
            branches:
              only: main
          steps:
            - heroku/deploy-via-git

jobs:
  test_code:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npx jest --detectOpenHandles
      - store_test_results:
          path: test-results

  deploy_to_heroku:
    executor:
      name: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git
